/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.mdre.adbSequences;

import com.arcadedb.ContextConfiguration;
import com.arcadedb.query.sql.SQLQueryEngine;
import com.arcadedb.server.ArcadeDBServer;
import com.arcadedb.server.ServerPlugin;

public class ADBSequencesPlugin implements ServerPlugin {

    @Override
    public void startService() {
        System.out.println("\nADBSequences plugin started");

    }

    @Override
    public void stopService() {
        ServerPlugin.super.stopService(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void configure(ArcadeDBServer arcadeDBServer, ContextConfiguration configuration) {
        System.out.println("\nPlugin configured");
        arcadeDBServer.getDatabaseNames().forEach((db) -> {
            final SQLQueryEngine sqlEngine = (SQLQueryEngine) arcadeDBServer.getDatabase(db).getQueryEngine("sql");
            sqlEngine.getFunctionFactory().register("sequence", new Sequence());
            sqlEngine.getFunctionFactory().register("createSequence", new CreateSequence());
            sqlEngine.getFunctionFactory().register("currentSequence", new CurrentSequence());
        });
        // REGISTER 'sequence' FUNCTION WITH FIXED 2 PARAMETERS (MIN/MAX=2)
        
    }

}
