/*
 * This source file was generated by the Gradle 'init' task
 */
package com.github.mdre.adbToolbox;

import com.arcadedb.ContextConfiguration;
import com.arcadedb.query.sql.SQLQueryEngine;
import com.arcadedb.server.ArcadeDBServer;
import com.arcadedb.server.ServerDatabase;
import com.arcadedb.server.ServerPlugin;

public class ADBToolboxPlugin implements ServerPlugin {

    @Override
    public void startService() {
        System.out.println("\nADBToolbox plugin started");
    }

    @Override
    public void stopService() {
        ServerPlugin.super.stopService(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    @Override
    public void configure(ArcadeDBServer arcadeDBServer, ContextConfiguration configuration) {
        System.out.println("\nConfiguring plugin...");
        Sequence sq = new Sequence();
        CreateSequence csq = new CreateSequence();
        CurrentSequence currentSequence = new CurrentSequence();
        CreateSequenceBind csb = new CreateSequenceBind();
        CreateAutoincrementBind caib = new CreateAutoincrementBind();
        arcadeDBServer.getDatabaseNames().forEach((dbName) -> {
            final SQLQueryEngine sqlEngine = (SQLQueryEngine) arcadeDBServer.getDatabase(dbName).getQueryEngine("sql");
            sqlEngine.getFunctionFactory().register("sequence", sq );
            sqlEngine.getFunctionFactory().register("createSequence", csq);
            sqlEngine.getFunctionFactory().register("currentSequence", currentSequence);
            sqlEngine.getFunctionFactory().register("createSequenceBind", csb);
            sqlEngine.getFunctionFactory().register("createAutoincrementBind", caib);
            System.out.println("Functions added: sequence, createSequence, currentSequence, createSequenceBind, createAutoincrementBind.");
            ServerDatabase db = arcadeDBServer.getDatabase(dbName);
            // process all binds in each database. 
            if (db.getSchema().existsType("___sequencesBinds")) {
                System.out.println("Sequences binds detected.");
                db.command("sql", "select distinct(sequenceType) from ___sequencesBinds")
                  .stream()
                  .forEach((sb) -> {
                    System.out.println("...");
                    System.out.println(db.getName() + " > "+sb.getProperty("sequenceType"));  
                    csb.registerListener(db, sb.getProperty("sequenceType"));
                });
                System.out.println("bind process end.");
            }
            if (db.getSchema().existsType("___autoincrementBinds")) {
                System.out.println("Autoincrement binds detected.");
                db.command("sql", "select distinct(Type) from ___autoincrementBinds")
                  .stream()
                  .forEach((sb) -> {
                    System.out.println("...");
                    System.out.println(db.getName() + " > "+sb.getProperty("Type"));  
                    caib.registerListener(db, sb.getProperty("Type"));
                });
                System.out.println("bind process end.");
            }
        });
        System.out.println("\nPlugin configured");
        
    }

}
